### ISSUE TITLE
Response is null when there is an error. This breaks @google-cloud/profiler

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/nodejs-common#172]
https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs depends on looking at a non-null response when there is an error to determine the server-specified backoff. Code for this is [here](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/blob/e038d697f84f1fe302b08b9add76cacdb3d6a049/ts/src/profiler.ts#L362-L372) and [here](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/blob/e038d697f84f1fe302b08b9add76cacdb3d6a049/ts/src/profiler.ts#L190-L208).

Starting with 0.18.X I believe the response is null when there is an error. The last version I see a non-null response when there is an error is 0.17.X.

**Comment by nolanmar511** [comment]
The `response` field within the error is also undefined in the 0.20

**Comment by JustinBeckwith** [comment]
@nolanmar511 I have a PR that I think? should resolve the issue in #182.  @ofrobots and I are planning to cut a release of this library today, so hopefully this works out :)

Any chance you could take the branch over in #182 for a spin and see if it fixes your issue?

**Comment by nolanmar511** [comment]
Sorry for the late response, just got back from vacation.

@JustinBeckwith -- This doesn't fix the issue for us.

We are expecting the "body" field of the response to have a field "error", which has a field "details", which is an array of objects, some of which may have the field "retryDelay". We need the "retryDelay" field.

Looking at #182, the change makes it so the response field of the error is returned. The body of this response does not have an "error" field. We already had this information, and it doesn't contain the portion of the response which we need.

**Comment by nolanmar511** [comment]
Any progress on this bug?

**Comment by nolanmar511** [comment]
Is there any timeline for this?
