### ISSUE TITLE
Release v2.1.1 is not backward compatible for Typescript Compilation.

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/nodejs-common#469]
I believe this is the same as #463 

While compiling https://github.com/googleapis/cloud-profiler-nodejs, we see the error message:
```
ts/src/profiler.ts:444:9 - error TS2345: Argument of type '{ method: string; uri: string; body: { deployment: Deployment; profileType: string[]; }; json: boolean; timeout: number; }' is not assignable to parameter of type 'DecorateRequestOptions'.
  Types of property 'method' are incompatible.
    Type 'string' is not assignable to type '"GET" | "HEAD" | "POST" | "DELETE" | "PUT" | "CONNECT" | "OPTIONS" | "TRACE" | "PATCH" | undefined'.
```

**Comment by nolanmar511** [comment]
Could a type guard for DecorateRequestOptions be provided?

@google-cloud/profiler makes an HTTP request which gives back a response body containing the request which should be used for the next HTTP request. A type guard for DecorateRequestOptions would be helpful for our use case.

**Comment by JustinBeckwith** [comment]
@bcoe thinking we should just back this off to `any`  in `teeny-request` to save ourselves pain ....

**Comment by nolanmar511** [comment]
This might be a helpful feature for a major version change. Exposing an enum of the types would simplify migration.

**Comment by nolanmar511** [comment]
To note one more issue we're having. After fixing the first error we see. After that I then see:
```
Argument of type '(err: Error | null, body?: object | undefined, response?: IncomingMessage | undefined) => void' is not assignable to parameter of type 'BodyResponseCallback'.
  Types of parameters 'response' and 'res' are incompatible.
    Type 'Response<any> | undefined' is not assignable to type 'IncomingMessage | undefined'.
      Type 'Response<any>' is missing the following properties from type 'IncomingMessage': httpVersion, httpVersionMajor, httpVersionMinor, connection, and 37 more.ts(2345)
```

https://github.com/googleapis/cloud-profiler-nodejs/pull/529 captures the changes I need to make to @google-cloud/profiler to be compatible with @google-cloud/common v2.1.1

**Comment by bcoe** [comment]
@nolanmar511 this should be fixed now, we rolled out a version of `teeny-request` that is less strict about request methods, can you confirm?

**Comment by nolanmar511** [comment]
We're still having some issues. Mainly the following error:
```
Thu Aug 15 06:07:28 UTC 2019: ts/src/profiler.ts:445:9 - error TS2345: Argument of type '(err: Error | null, body?: object | undefined, response?: IncomingMessage | undefined) => void' is not assignable to parameter of type 'BodyResponseCallback'.
Thu Aug 15 06:07:28 UTC 2019: Types of parameters 'response' and 'res' are incompatible.
Thu Aug 15 06:07:28 UTC 2019: Type 'Response<any> | undefined' is not assignable to type 'IncomingMessage | undefined'.
Thu Aug 15 06:07:28 UTC 2019: Type 'Response<any>' is missing the following properties from type 'IncomingMessage': 
```

Compliation is also broken in some places where we stub in our tests -- both of these issues are related to the change in the type for the call back method which `request()` takes.

I updated https://github.com/googleapis/cloud-profiler-nodejs/pull/529 captures the changes we would need to make to use the latest version of @google-cloud/common.

**Comment by bcoe** [comment]
@nolanmar511 are you at least unblocked? I understand @JustinBeckwith's motivation in not wanting to ship `@types/request` in `teeny-request`, as the libraries types are going to continue to diverge over time. Hindsight 20/20 this types change should have been a `major` change.

**Comment by nolanmar511** [comment]
I'll merge in  googleapis/cloud-profiler-nodejs#529, and cloud-profiler-nodejs should be unblocked. 
Thanks!
